// Code generated by protoc-gen-go.
// source: txnsvc.proto
// DO NOT EDIT!

/*
Package txnsvc is a generated protocol buffer package.

It is generated from these files:
	txnsvc.proto

It has these top-level messages:
	TxnStepReq
	TxnStepResp
*/
package txnsvc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TxnStepReq struct {
	StepFunc         *string `protobuf:"bytes,1,req,name=StepFunc" json:"StepFunc,omitempty"`
	Context          []byte  `protobuf:"bytes,2,req,name=Context" json:"Context,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TxnStepReq) Reset()                    { *m = TxnStepReq{} }
func (m *TxnStepReq) String() string            { return proto.CompactTextString(m) }
func (*TxnStepReq) ProtoMessage()               {}
func (*TxnStepReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TxnStepReq) GetStepFunc() string {
	if m != nil && m.StepFunc != nil {
		return *m.StepFunc
	}
	return ""
}

func (m *TxnStepReq) GetContext() []byte {
	if m != nil {
		return m.Context
	}
	return nil
}

type TxnStepResp struct {
	Error            *string `protobuf:"bytes,1,req,name=Error" json:"Error,omitempty"`
	Resp             []byte  `protobuf:"bytes,2,req,name=Resp" json:"Resp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TxnStepResp) Reset()                    { *m = TxnStepResp{} }
func (m *TxnStepResp) String() string            { return proto.CompactTextString(m) }
func (*TxnStepResp) ProtoMessage()               {}
func (*TxnStepResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TxnStepResp) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *TxnStepResp) GetResp() []byte {
	if m != nil {
		return m.Resp
	}
	return nil
}

func init() {
	proto.RegisterType((*TxnStepReq)(nil), "txnsvc.TxnStepReq")
	proto.RegisterType((*TxnStepResp)(nil), "txnsvc.TxnStepResp")
}

func init() { proto.RegisterFile("txnsvc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 113 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0xa9, 0xc8, 0x2b,
	0x2e, 0x4b, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0xf4, 0xb9, 0xb8,
	0x42, 0x2a, 0xf2, 0x82, 0x4b, 0x52, 0x0b, 0x82, 0x52, 0x0b, 0x85, 0x04, 0xb8, 0x38, 0x40, 0x4c,
	0xb7, 0xd2, 0xbc, 0x64, 0x09, 0x46, 0x05, 0x26, 0x0d, 0x4e, 0x21, 0x7e, 0x2e, 0x76, 0xe7, 0xfc,
	0xbc, 0x92, 0xd4, 0x8a, 0x12, 0x09, 0x26, 0xa0, 0x00, 0x8f, 0x92, 0x16, 0x17, 0x37, 0x5c, 0x43,
	0x71, 0x81, 0x10, 0x2f, 0x17, 0xab, 0x6b, 0x51, 0x51, 0x7e, 0x11, 0x54, 0x39, 0x0f, 0x17, 0x0b,
	0x48, 0x18, 0xa2, 0x16, 0x10, 0x00, 0x00, 0xff, 0xff, 0x54, 0x5a, 0x87, 0xdf, 0x73, 0x00, 0x00,
	0x00,
}
