# find . -name "*.t" | awk {print # prove -v } >> all_tests.sh
# prove -v ./tests/basic/cloudsync-sanity.t
# prove -v ./tests/basic/volume-snapshot-xml.t
# prove -v ./tests/basic/0symbol-check.t
# prove -v ./tests/basic/afr/afr-up.t
# prove -v ./tests/basic/afr/resolve.t
# prove -v ./tests/basic/afr/heal-quota.t
# prove -v ./tests/basic/afr/quorum.t
# prove -v ./tests/basic/afr/gfid-heal.t
# prove -v ./tests/basic/afr/sparse-file-self-heal.t
# prove -v ./tests/basic/afr/self-heal.t
# prove -v ./tests/basic/afr/replace-brick-self-heal.t
# prove -v ./tests/basic/afr/split-brain-healing.t
# prove -v ./tests/basic/afr/stale-file-lookup.t
# prove -v ./tests/basic/afr/self-heald.t
# prove -v ./tests/basic/afr/afr-read-hash-mode.t
# prove -v ./tests/basic/afr/afr-no-fsync.t
# prove -v ./tests/basic/afr/gfid-self-heal.t
# prove -v ./tests/basic/afr/gfid-mismatch-resolution-with-fav-child-policy.t
# prove -v ./tests/basic/afr/read-subvol-entry.t
# prove -v ./tests/basic/afr/gfid-mismatch.t
# prove -v ./tests/basic/afr/arbiter-statfs.t
# prove -v ./tests/basic/afr/split-brain-heal-info.t
# prove -v ./tests/basic/afr/split-brain-favorite-child-policy.t
# prove -v ./tests/basic/afr/lk-quorum.t
# prove -v ./tests/basic/afr/gfid-mismatch-resolution-with-cli.t
# prove -v ./tests/basic/afr/metadata-self-heal.t
# prove -v ./tests/basic/afr/arbiter.t
# prove -v ./tests/basic/afr/durability-off.t
# prove -v ./tests/basic/afr/arbiter-remove-brick.t
# prove -v ./tests/basic/afr/root-squash-self-heal.t
# prove -v ./tests/basic/afr/data-self-heal.t
# prove -v ./tests/basic/afr/granular-esh/replace-brick.t
# prove -v ./tests/basic/afr/granular-esh/cli.t
# prove -v ./tests/basic/afr/granular-esh/conservative-merge.t
# prove -v ./tests/basic/afr/granular-esh/add-brick.t
# prove -v ./tests/basic/afr/granular-esh/granular-esh.t
# prove -v ./tests/basic/afr/granular-esh/granular-indices-but-non-granular-heal.t
# prove -v ./tests/basic/afr/arbiter-cli.t
# prove -v ./tests/basic/afr/read-subvol-data.t
# prove -v ./tests/basic/afr/client-side-heal.t
# prove -v ./tests/basic/afr/entry-self-heal.t
# prove -v ./tests/basic/afr/split-brain-open.t
# prove -v ./tests/basic/afr/tarissue.t
# prove -v ./tests/basic/afr/heal-info.t
# prove -v ./tests/basic/afr/arbiter-add-brick.t
# prove -v ./tests/basic/afr/split-brain-resolution.t
# prove -v ./tests/basic/afr/arbiter-mount.t
# prove -v ./tests/basic/afr/add-brick-self-heal.t
# prove -v ./tests/basic/afr/inodelk.t
# prove -v ./tests/basic/gfproxy.t
# prove -v ./tests/basic/ctime/ctime-glfs-init.t
# prove -v ./tests/basic/ctime/ctime-heal-symlinks.t
# prove -v ./tests/basic/glusterd/arbiter-volume.t
# prove -v ./tests/basic/glusterd/arbiter-volume-probe.t
# prove -v ./tests/basic/glusterd/disperse-create.t
# prove -v ./tests/basic/glusterd/heald.t
# prove -v ./tests/basic/glusterd/volfile_server_switch.t
# prove -v ./tests/basic/volume-snapshot-clone.t
# prove -v ./tests/basic/bd.t
# prove -v ./tests/basic/peer-parsing.t
# prove -v ./tests/basic/mgmt_v3-locks.t
# prove -v ./tests/basic/sdfs-sanity.t
# prove -v ./tests/basic/tier/unlink-during-migration.t
# prove -v ./tests/basic/tier/tier.t
# prove -v ./tests/basic/tier/file_with_spaces.t
# prove -v ./tests/basic/tier/bug-1214222-directories_missing_after_attach_tier.t
# prove -v ./tests/basic/tier/new-tier-cmds.t
# prove -v ./tests/basic/tier/legacy-many.t
# prove -v ./tests/basic/tier/tier-snapshot.t
# prove -v ./tests/basic/tier/readdir-during-migration.t
# prove -v ./tests/basic/tier/bug-1260185-donot-allow-detach-commit-unnecessarily.t
# prove -v ./tests/basic/tier/fops-during-migration.t
# prove -v ./tests/basic/tier/tierd_check.t
# prove -v ./tests/basic/tier/tier_lookup_heal.t
# prove -v ./tests/basic/tier/locked_file_migration.t
# prove -v ./tests/basic/tier/fops-during-migration-pause.t
# prove -v ./tests/basic/tier/frequency-counters.t
# prove -v ./tests/basic/tier/record-metadata-heat.t
# prove -v ./tests/basic/tier/tier-heald.t
# prove -v ./tests/basic/tier/ctr-rename-overwrite.t
# prove -v ./tests/basic/changelog/changelog-rename.t
# prove -v ./tests/basic/exports_parsing.t
# prove -v ./tests/basic/ios-dump.t
# prove -v ./tests/basic/xlator-pass-through-sanity.t
# prove -v ./tests/basic/volume-snapshot.t
# prove -v ./tests/basic/inode-quota-enforcing.t
# prove -v ./tests/basic/inode-leak.t
# prove -v ./tests/basic/rpc-coverage.t
# prove -v ./tests/basic/stats-dump.t
# prove -v ./tests/basic/multiplex.t
# prove -v ./tests/basic/mpx-compat.t
# prove -v ./tests/basic/hardlink-limit.t
# prove -v ./tests/basic/posix/zero-fill-enospace.t
# prove -v ./tests/basic/posix/shared-statfs.t
# prove -v ./tests/basic/fops-sanity.t
# prove -v ./tests/basic/meta.t
# prove -v ./tests/basic/distribute/lookup.t
# prove -v ./tests/basic/distribute/non-root-unlink-stale-linkto.t
# prove -v ./tests/basic/distribute/force-migration.t
# prove -v ./tests/basic/distribute/rebal-all-nodes-migrate.t
# prove -v ./tests/basic/distribute/bug-1265677-use-readdirp.t
# prove -v ./tests/basic/distribute/throttle-rebal.t
# prove -v ./tests/basic/volume-status.t
# prove -v ./tests/basic/quota.t
# prove -v ./tests/basic/volfile-sanity.t
# prove -v ./tests/basic/gfid-access.t
# prove -v ./tests/basic/quota-anon-fd-nfs.t
# prove -v ./tests/basic/cdc.t
# prove -v ./tests/basic/quick-read-with-upcall.t
# prove -v ./tests/basic/quota_aux_mount.t
# prove -v ./tests/basic/volume.t
# prove -v ./tests/basic/pgfid-feat.t
# prove -v ./tests/basic/fop-sampling.t
# prove -v ./tests/basic/quota-ancestry-building.t
# prove -v ./tests/basic/nufa.t
# prove -v ./tests/basic/nl-cache.t
# prove -v ./tests/basic/namespace.t
# prove -v ./tests/basic/gfapi/gfapi-async-calls-test.t
# prove -v ./tests/basic/gfapi/bug1291259.t
# prove -v ./tests/basic/gfapi/anonymous_fd.t
# prove -v ./tests/basic/gfapi/glfs_xreaddirplus_r.t
# prove -v ./tests/basic/gfapi/gfapi-ssl-test.t
# prove -v ./tests/basic/gfapi/mandatory-lock-optimal.t
# prove -v ./tests/basic/gfapi/gfapi-dup.t
# prove -v ./tests/basic/gfapi/bug-1241104.t
# prove -v ./tests/basic/gfapi/gfapi-trunc.t
# prove -v ./tests/basic/gfapi/sink.t
# prove -v ./tests/basic/gfapi/libgfapi-fini-hang.t
# prove -v ./tests/basic/gfapi/upcall-register-api.t
# prove -v ./tests/basic/gfapi/gfapi-load-volfile.t
# prove -v ./tests/basic/gfapi/glfs_sysrq.t
# prove -v ./tests/basic/gfapi/upcall-cache-invalidate.t
# prove -v ./tests/basic/gfapi/glfd-lkowner.t
# prove -v ./tests/basic/mount-nfs-auth.t
# prove -v ./tests/basic/op_errnos.t
# prove -v ./tests/basic/quota-nfs.t
# prove -v ./tests/basic/mount.t
# prove -v ./tests/basic/geo-replication/marker-xattrs.t
# prove -v ./tests/basic/posixonly.t
# prove -v ./tests/basic/uss.t
# prove -v ./tests/basic/md-cache/bug-1317785.t
# prove -v ./tests/basic/md-cache/bug-1418249.t
# prove -v ./tests/basic/quota-rename.t
# prove -v ./tests/basic/netgroup_parsing.t
# prove -v ./tests/basic/first-test.t
# prove -v ./tests/basic/jbr/jbr-volgen.t
# prove -v ./tests/basic/jbr/jbr.t
# prove -v ./tests/basic/ec/ec-internal-xattrs.t
# prove -v ./tests/basic/ec/ec-fast-fgetxattr.t
# prove -v ./tests/basic/ec/self-heal.t
# prove -v ./tests/basic/ec/ec-optimistic-changelog.t
# prove -v ./tests/basic/ec/lock-contention.t
# prove -v ./tests/basic/ec/ec-4-1.t
# prove -v ./tests/basic/ec/statedump.t
# prove -v ./tests/basic/ec/ec-readdir.t
# prove -v ./tests/basic/ec/ec-up.t
# prove -v ./tests/basic/ec/ec-read-policy.t
# prove -v ./tests/basic/ec/ec-stripe.t
# prove -v ./tests/basic/ec/ec-new-entry.t
# prove -v ./tests/basic/ec/ec-fix-openfd.t
# prove -v ./tests/basic/ec/ec-rebalance.t
# prove -v ./tests/basic/ec/ec-anonymous-fd.t
# prove -v ./tests/basic/ec/quota.t
# prove -v ./tests/basic/ec/ec-notify.t
# prove -v ./tests/basic/ec/ec-5-2.t
# prove -v ./tests/basic/ec/ec-cpu-extensions.t
# prove -v ./tests/basic/ec/ec-discard.t
# prove -v ./tests/basic/ec/ec-root-heal.t
# prove -v ./tests/basic/ec/ec.t
# prove -v ./tests/basic/ec/ec-background-heals.t
# prove -v ./tests/basic/ec/ec-fallocate.t
# prove -v ./tests/basic/ec/ec-data-heal.t
# prove -v ./tests/basic/ec/ec-3-1.t
# prove -v ./tests/basic/ec/nfs.t
# prove -v ./tests/basic/ec/ec-1468261.t
# prove -v ./tests/basic/ec/heal-info.t
# prove -v ./tests/basic/ec/ec-6-2.t
# prove -v ./tests/basic/ec/ec-seek.t
# prove -v ./tests/basic/ec/dht-rename.t
# prove -v ./tests/performance/quick-read.t
# prove -v ./tests/performance/open-behind.t
# prove -v ./tests/encryption/crypt.t
# prove -v ./tests/bugs/access-control/bug-1051896.t
# prove -v ./tests/bugs/access-control/bug-958691.t
# prove -v ./tests/bugs/access-control/bug-1387241.t
# prove -v ./tests/bugs/access-control/bug-887098-gmount-crash.t
# prove -v ./tests/bugs/io-cache/bug-read-hang.t
# prove -v ./tests/bugs/io-cache/bug-858242.t
# prove -v ./tests/bugs/bug-1371806_acl.t
# prove -v ./tests/bugs/upcall/bug-upcall-stat.t
# prove -v ./tests/bugs/upcall/bug-1458127.t
# prove -v ./tests/bugs/upcall/bug-1394131.t
# prove -v ./tests/bugs/upcall/bug-1227204.t
# prove -v ./tests/bugs/upcall/bug-1369430.t
# prove -v ./tests/bugs/upcall/bug-1422776.t
# prove -v ./tests/bugs/trace/bug-797171.t
# prove -v ./tests/bugs/glusterd/snapshot-operations.t
# prove -v ./tests/bugs/glusterd/validating-options-for-striped-replicated-volume.t
# prove -v ./tests/bugs/glusterd/bug-1085330-and-bug-916549.t
# prove -v ./tests/bugs/glusterd/optimized-basic-testcases-in-cluster.t
# prove -v ./tests/bugs/glusterd/brick-mux.t
# prove -v ./tests/bugs/glusterd/daemon-log-level-option.t
# prove -v ./tests/bugs/glusterd/rebalance-in-cluster.t
# prove -v ./tests/bugs/glusterd/validating-server-quorum.t
# prove -v ./tests/bugs/glusterd/bug-949930.t
# prove -v ./tests/bugs/glusterd/bug-948729/bug-948729.t
# prove -v ./tests/bugs/glusterd/bug-948729/bug-948729-force.t
# prove -v ./tests/bugs/glusterd/bug-948729/bug-948729-mode-script.t
# prove -v ./tests/bugs/glusterd/reset-brick-and-daemons-follow-quorum.t
# prove -v ./tests/bugs/glusterd/quorum-validation.t
# prove -v ./tests/bugs/glusterd/enable-shared-storage-and-remove-brick-validation.t
# prove -v ./tests/bugs/glusterd/bug-1482906-peer-file-blank-line.t
# prove -v ./tests/bugs/glusterd/add-brick-and-validate-replicated-volume-options.t
# prove -v ./tests/bugs/glusterd/sync-post-glusterd-restart.t
# prove -v ./tests/bugs/glusterd/remove-brick-in-cluster.t
# prove -v ./tests/bugs/glusterd/removing-multiple-bricks-in-single-remove-brick-command.t
# prove -v ./tests/bugs/glusterd/rebalance-operations-in-single-node.t
# prove -v ./tests/bugs/glusterd/stale-brick-proc-brick-mux.t
# prove -v ./tests/bugs/glusterd/bug-824753.t
# prove -v ./tests/bugs/glusterd/bug-1091935-brick-order-check-from-cli-to-glusterd.t
# prove -v ./tests/bugs/glusterd/bug-1242875-do-not-pass-volinfo-quota.t
# prove -v ./tests/bugs/glusterd/replace-brick-operations.t
# prove -v ./tests/bugs/glusterd/mgmt-handshake-and-volume-sync-post-glusterd-restart.t
# prove -v ./tests/bugs/glusterd/bug-1238706-daemons-stop-on-peer-cleanup.t
# prove -v ./tests/bugs/glusterd/optimized-basic-testcases.t
# prove -v ./tests/bugs/glusterd/bug-1303028-Rebalance-glusterd-rpc-connection-issue.t
# prove -v ./tests/bugs/glusterd/bug-857330/xml.t
# prove -v ./tests/bugs/glusterd/bug-857330/normal.t
# prove -v ./tests/bugs/glusterd/bug-1070734.t
# prove -v ./tests/bugs/glusterd/859927/repl.t
# prove -v ./tests/bugs/glusterd/brick-mux-validation.t
# prove -v ./tests/bugs/glusterd/remove-brick-testcases.t
# prove -v ./tests/bugs/tier/bug-1279376-rename-demoted-file.t
# prove -v ./tests/bugs/tier/bug-1205545-CTR-and-trash-integration.t
# prove -v ./tests/bugs/changelog/bug-1208470.t
# prove -v ./tests/bugs/changelog/bug-1211327.t
# prove -v ./tests/bugs/changelog/bug-1321955.t
# prove -v ./tests/bugs/changelog/bug-1225542.t
# prove -v ./tests/bugs/bug-1110262.t
# prove -v ./tests/bugs/quick-read/bz1523599/bz1523599.t
# prove -v ./tests/bugs/quick-read/bug-846240.t
# prove -v ./tests/bugs/error-gen/bug-767095.t
# prove -v ./tests/bugs/stripe/bug-1002207.t
# prove -v ./tests/bugs/stripe/bug-1111454.t
# prove -v ./tests/bugs/posix/bug-gfid-path.t
# prove -v ./tests/bugs/posix/bug-1034716.t
# prove -v ./tests/bugs/posix/bug-765380.t
# prove -v ./tests/bugs/posix/bug-1040275-brick-uid-reset-on-volume-restart.t
# prove -v ./tests/bugs/posix/disallow-gfid-volumeid-fremovexattr.t
# prove -v ./tests/bugs/posix/bug-1360679.t
# prove -v ./tests/bugs/posix/bug-1175711.t
# prove -v ./tests/bugs/posix/bug-1113960.t
# prove -v ./tests/bugs/posix/bug-990028.t
# prove -v ./tests/bugs/posix/bug-1122028.t
# prove -v ./tests/bugs/posix/disallow-gfid-volumeid-removexattr.t
# prove -v ./tests/bugs/readdir-ahead/bug-1512437.t
# prove -v ./tests/bugs/readdir-ahead/bug-1446516.t
# prove -v ./tests/bugs/readdir-ahead/bug-1436090.t
# prove -v ./tests/bugs/readdir-ahead/bug-1439640.t
# prove -v ./tests/bugs/core/bug-913544.t
# prove -v ./tests/bugs/core/bug-903336.t
# prove -v ./tests/bugs/core/bug-1111557.t
# prove -v ./tests/bugs/core/bug-1402841.t-mt-dir-scan-race.t
# prove -v ./tests/bugs/core/bug-1110917.t
# prove -v ./tests/bugs/core/bug-1168803-snapd-option-validation-fix.t
# prove -v ./tests/bugs/core/bug-1421721-mpx-toggle.t
# prove -v ./tests/bugs/core/io-stats-1322825.t
# prove -v ./tests/bugs/core/bug-1117951.t
# prove -v ./tests/bugs/core/bug-927616.t
# prove -v ./tests/bugs/core/log-bug-1362520.t
# prove -v ./tests/bugs/core/bug-845213.t
# prove -v ./tests/bugs/core/bug-908146.t
# prove -v ./tests/bugs/core/bug-986429.t
# prove -v ./tests/bugs/core/bug-1432542-mpx-restart-crash.t
# prove -v ./tests/bugs/core/bug-834465.t
# prove -v ./tests/bugs/core/bug-924075.t
# prove -v ./tests/bugs/core/bug-1135514-allow-setxattr-with-null-value.t
# prove -v ./tests/bugs/core/949327.t
# prove -v ./tests/bugs/core/bug-949242.t
# prove -v ./tests/bugs/core/multiplex-limit-issue-151.t
# prove -v ./tests/bugs/core/bug-1119582.t
# prove -v ./tests/bugs/distribute/bug-1161156.t
# prove -v ./tests/bugs/distribute/bug-1117851.t
# prove -v ./tests/bugs/distribute/bug-921408.t
# prove -v ./tests/bugs/distribute/bug-853258.t
# prove -v ./tests/bugs/distribute/bug-924265.t
# prove -v ./tests/bugs/distribute/bug-1190734.t
# prove -v ./tests/bugs/distribute/bug-1389697.t
# prove -v ./tests/bugs/distribute/bug-1042725.t
# prove -v ./tests/bugs/distribute/bug-1161311.t
# prove -v ./tests/bugs/distribute/bug-1099890.t
# prove -v ./tests/bugs/distribute/bug-882278.t
# prove -v ./tests/bugs/distribute/bug-860663.t
# prove -v ./tests/bugs/distribute/bug-1543279.t
# prove -v ./tests/bugs/distribute/bug-1368012.t
# prove -v ./tests/bugs/distribute/bug-1125824.t
# prove -v ./tests/bugs/distribute/bug-961615.t
# prove -v ./tests/bugs/distribute/bug-912564.t
# prove -v ./tests/bugs/distribute/bug-1086228.t
# prove -v ./tests/bugs/distribute/bug-907072.t
# prove -v ./tests/bugs/distribute/bug-915554.t
# prove -v ./tests/bugs/distribute/bug-1066798.t
# prove -v ./tests/bugs/distribute/bug-884455.t
# prove -v ./tests/bugs/distribute/bug-884597.t
# prove -v ./tests/bugs/distribute/bug-862967.t
# prove -v ./tests/bugs/distribute/bug-1122443.t
# prove -v ./tests/bugs/distribute/bug-973073.t
# prove -v ./tests/bugs/distribute/bug-1193636.t
# prove -v ./tests/bugs/distribute/bug-1247563.t
# prove -v ./tests/bugs/distribute/bug-1088231.t
# prove -v ./tests/bugs/distribute/bug-1204140.t
# prove -v ./tests/bugs/glusterfs/bug-861015-log.t
# prove -v ./tests/bugs/glusterfs/bug-866459.t
# prove -v ./tests/bugs/glusterfs/bug-906646.t
# prove -v ./tests/bugs/glusterfs/bug-844688.t
# prove -v ./tests/bugs/glusterfs/bug-861015-index.t
# prove -v ./tests/bugs/glusterfs/bug-902610.t
# prove -v ./tests/bugs/glusterfs/bug-1482528.t
# prove -v ./tests/bugs/glusterfs/bug-893378.t
# prove -v ./tests/bugs/glusterfs/bug-811493.t
# prove -v ./tests/bugs/glusterfs/bug-869724.t
# prove -v ./tests/bugs/glusterfs/bug-879490.t
# prove -v ./tests/bugs/glusterfs/bug-860297.t
# prove -v ./tests/bugs/glusterfs/bug-895235.t
# prove -v ./tests/bugs/glusterfs/bug-873962-spb.t
# prove -v ./tests/bugs/glusterfs/bug-893338.t
# prove -v ./tests/bugs/glusterfs/bug-873962.t
# prove -v ./tests/bugs/glusterfs/bug-856455.t
# prove -v ./tests/bugs/glusterfs/bug-867253.t
# prove -v ./tests/bugs/glusterfs/bug-879494.t
# prove -v ./tests/bugs/glusterfs/bug-853690.t
# prove -v ./tests/bugs/glusterfs/bug-892730.t
# prove -v ./tests/bugs/glusterfs/bug-872923.t
# prove -v ./tests/bugs/glusterfs/bug-848251.t
# prove -v ./tests/bugs/glusterfs/bug-896431.t
# prove -v ./tests/bugs/transport/bug-873367.t
# prove -v ./tests/bugs/bug-1368312.t
# prove -v ./tests/bugs/protocol/bug-808400.t
# prove -v ./tests/bugs/protocol/bug-808400-repl.t
# prove -v ./tests/bugs/protocol/bug-1321578.t
# prove -v ./tests/bugs/protocol/bug-1433815-auth-allow.t
# prove -v ./tests/bugs/protocol/bug-762989.t
# prove -v ./tests/bugs/protocol/bug-808400-dist.t
# prove -v ./tests/bugs/protocol/bug-808400-stripe.t
# prove -v ./tests/bugs/fuse/many-groups-for-acl.t
# prove -v ./tests/bugs/fuse/bug-1030208.t
# prove -v ./tests/bugs/fuse/bug-963678.t
# prove -v ./tests/bugs/fuse/bug-1126048.t
# prove -v ./tests/bugs/fuse/bug-858215.t
# prove -v ./tests/bugs/fuse/bug-1309462.t
# prove -v ./tests/bugs/fuse/bug-985074.t
# prove -v ./tests/bugs/fuse/bug-983477.t
# prove -v ./tests/bugs/fuse/bug-1336818.t
# prove -v ./tests/bugs/fuse/bug-858488-min-free-disk.t
# prove -v ./tests/bugs/fuse/bug-1283103.t
# prove -v ./tests/bugs/fuse/bug-924726.t
# prove -v ./tests/bugs/replicate/bug-1363721.t
# prove -v ./tests/bugs/replicate/bug-1448804-check-quorum-type-values.t
# prove -v ./tests/bugs/replicate/bug-802417.t
# prove -v ./tests/bugs/replicate/bug-1498570-client-iot-graph-check.t
# prove -v ./tests/bugs/replicate/bug-1032927.t
# prove -v ./tests/bugs/replicate/bug-978794.t
# prove -v ./tests/bugs/replicate/bug-1221481-allow-fops-on-dir-split-brain.t
# prove -v ./tests/bugs/replicate/bug-957877.t
# prove -v ./tests/bugs/replicate/bug-1058797.t
# prove -v ./tests/bugs/replicate/bug-765564.t
# prove -v ./tests/bugs/replicate/bug-1480525.t
# prove -v ./tests/bugs/replicate/bug-1305031-block-reads-on-metadata-sbrain.t
# prove -v ./tests/bugs/replicate/bug-1238398-split-brain-resolution.t
# prove -v ./tests/bugs/replicate/bug-1438255-do-not-mark-self-accusing-xattrs.t
# prove -v ./tests/bugs/replicate/bug-979365.t
# prove -v ./tests/bugs/replicate/bug-1250170-fsync.t
# prove -v ./tests/bugs/replicate/bug-1365455.t
# prove -v ./tests/bugs/replicate/bug-880898.t
# prove -v ./tests/bugs/replicate/bug-1341650.t
# prove -v ./tests/bugs/replicate/bug-1335652.t
# prove -v ./tests/bugs/replicate/bug-977797.t
# prove -v ./tests/bugs/replicate/bug-886998.t
# prove -v ./tests/bugs/replicate/bug-1591193-assign-gfid-and-heal.t
# prove -v ./tests/bugs/replicate/bug-767585-gfid.t
# prove -v ./tests/bugs/replicate/bug-1046624.t
# prove -v ./tests/bugs/replicate/886998/strict-readdir.t
# prove -v ./tests/bugs/replicate/bug-986905.t
# prove -v ./tests/bugs/replicate/bug-1561129-enospc.t
# prove -v ./tests/bugs/replicate/bug-1266876-allow-reset-brick-for-same-path.t
# prove -v ./tests/bugs/replicate/bug-1386188-sbrain-fav-child.t
# prove -v ./tests/bugs/replicate/bug-1539358-split-brain-detection.t
# prove -v ./tests/bugs/replicate/bug-865825.t
# prove -v ./tests/bugs/replicate/bug-821056.t
# prove -v ./tests/bugs/replicate/bug-1417522-block-split-brain-resolution.t
# prove -v ./tests/bugs/replicate/bug-921231.t
# prove -v ./tests/bugs/replicate/bug-1139230.t
# prove -v ./tests/bugs/replicate/bug-1325792.t
# prove -v ./tests/bugs/replicate/bug-913051.t
# prove -v ./tests/bugs/replicate/bug-1468279-source-not-blaming-sinks.t
# prove -v ./tests/bugs/replicate/bug-1290965-detect-bitrotten-objects.t
# prove -v ./tests/bugs/replicate/bug-1101647.t
# prove -v ./tests/bugs/replicate/bug-916226.t
# prove -v ./tests/bugs/replicate/bug-1402730.t
# prove -v ./tests/bugs/replicate/bug-1190069-afr-stale-index-entries.t
# prove -v ./tests/bugs/replicate/bug-1132102.t
# prove -v ./tests/bugs/replicate/bug-1297695.t
# prove -v ./tests/bugs/replicate/bug-918437-sh-mtime.t
# prove -v ./tests/bugs/replicate/bug-1130892.t
# prove -v ./tests/bugs/replicate/bug-1292379.t
# prove -v ./tests/bugs/replicate/bug-1473026.t
# prove -v ./tests/bugs/replicate/bug-1477169-entry-selfheal-rename.t
# prove -v ./tests/bugs/replicate/bug-1015990-rep.t
# prove -v ./tests/bugs/replicate/bug-859581.t
# prove -v ./tests/bugs/replicate/bug-1015990.t
# prove -v ./tests/bugs/replicate/bug-976800.t
# prove -v ./tests/bugs/replicate/bug-1340623-mkdir-fails-remove-brick-started.t
# prove -v ./tests/bugs/replicate/bug-888174.t
# prove -v ./tests/bugs/replicate/bug-1238508-self-heal.t
# prove -v ./tests/bugs/replicate/bug-1134691-afr-lookup-metadata-heal.t
# prove -v ./tests/bugs/replicate/bug-884328.t
# prove -v ./tests/bugs/replicate/bug-1433571-undo-pending-only-on-up-bricks.t
# prove -v ./tests/bugs/replicate/bug-1180545.t
# prove -v ./tests/bugs/replicate/bug-1037501.t
# prove -v ./tests/bugs/replicate/bug-1493415-gfid-heal.t
# prove -v ./tests/bugs/replicate/bug-830665.t
# prove -v ./tests/bugs/replicate/bug-1408712.t
# prove -v ./tests/bugs/snapshot/bug-1178079.t
# prove -v ./tests/bugs/snapshot/bug-1597662.t
# prove -v ./tests/bugs/snapshot/bug-1162462.t
# prove -v ./tests/bugs/snapshot/bug-1399598-uss-with-ssl.t
# prove -v ./tests/bugs/snapshot/bug-1112613.t
# prove -v ./tests/bugs/snapshot/bug-1113975.t
# prove -v ./tests/bugs/snapshot/bug-1090042.t
# prove -v ./tests/bugs/snapshot/bug-1260848.t
# prove -v ./tests/bugs/snapshot/bug-1162498.t
# prove -v ./tests/bugs/snapshot/bug-1109770.t
# prove -v ./tests/bugs/snapshot/bug-1205592.t
# prove -v ./tests/bugs/snapshot/bug-1482023-snpashot-issue-with-other-processes-accessing-mounted-path.t
# prove -v ./tests/bugs/snapshot/bug-1087203.t
# prove -v ./tests/bugs/snapshot/bug-1275616.t
# prove -v ./tests/bugs/snapshot/bug-1049834.t
# prove -v ./tests/bugs/snapshot/bug-1202436-calculate-quota-cksum-during-snap-restore.t
# prove -v ./tests/bugs/snapshot/bug-1045333.t
# prove -v ./tests/bugs/snapshot/bug-1155042-dont-display-deactivated-snapshots.t
# prove -v ./tests/bugs/snapshot/bug-1109889.t
# prove -v ./tests/bugs/snapshot/bug-1316437.t
# prove -v ./tests/bugs/snapshot/bug-1232430.t
# prove -v ./tests/bugs/snapshot/bug-1140162-file-snapshot-features-encrypt-opts-validation.t
# prove -v ./tests/bugs/snapshot/bug-1064768.t
# prove -v ./tests/bugs/snapshot/bug-1111041.t
# prove -v ./tests/bugs/snapshot/bug-1227646.t
# prove -v ./tests/bugs/snapshot/bug-1250387.t
# prove -v ./tests/bugs/snapshot/bug-1167580-set-proper-uid-and-gid-during-nfs-access.t
# prove -v ./tests/bugs/snapshot/bug-1279327.t
# prove -v ./tests/bugs/snapshot/bug-1512451-snapshot-creation-failed-after-brick-reset.t
# prove -v ./tests/bugs/snapshot/bug-1166197.t
# prove -v ./tests/bugs/snapshot/bug-1157991.t
# prove -v ./tests/bugs/snapshot/bug-1322772-real-path-fix-for-snapshot.t
# prove -v ./tests/bugs/snapshot/bug-1168875.t
# prove -v ./tests/bugs/io-stats/bug-1598548.t
# prove -v ./tests/bugs/index/bug-1559004-EMLINK-handling.t
# prove -v ./tests/bugs/heal-symlinks.t
# prove -v ./tests/bugs/read-only/bug-1134822-read-only-default-in-graph.t
# prove -v ./tests/bugs/quota/bug-1038598.t
# prove -v ./tests/bugs/quota/bug-1293601.t
# prove -v ./tests/bugs/quota/bug-1288474.t
# prove -v ./tests/bugs/quota/bug-1287996.t
# prove -v ./tests/bugs/quota/bug-1292020.t
# prove -v ./tests/bugs/quota/bug-1243798.t
# prove -v ./tests/bugs/quota/bug-1250582-volume-reset-should-not-remove-quota-quota-deem-statfs.t
# prove -v ./tests/bugs/quota/bug-1087198.t
# prove -v ./tests/bugs/quota/bug-1235182.t
# prove -v ./tests/bugs/quota/afr-quota-xattr-mdata-heal.t
# prove -v ./tests/bugs/quota/bug-1178130.t
# prove -v ./tests/bugs/quota/bug-1035576.t
# prove -v ./tests/bugs/quota/bug-1260545.t
# prove -v ./tests/bugs/quota/bug-1104692.t
# prove -v ./tests/bugs/quota/bug-1153964.t
# prove -v ./tests/bugs/glusterfs-server/bug-861542.t
# prove -v ./tests/bugs/glusterfs-server/bug-905864.t
# prove -v ./tests/bugs/glusterfs-server/bug-864222.t
# prove -v ./tests/bugs/glusterfs-server/bug-887145.t
# prove -v ./tests/bugs/glusterfs-server/bug-877992.t
# prove -v ./tests/bugs/glusterfs-server/bug-912297.t
# prove -v ./tests/bugs/glusterfs-server/bug-852147.t
# prove -v ./tests/bugs/glusterfs-server/bug-889996.t
# prove -v ./tests/bugs/glusterfs-server/bug-873549.t
# prove -v ./tests/bugs/glusterfs-server/bug-904300.t
# prove -v ./tests/bugs/bug-1371806_1.t
# prove -v ./tests/bugs/gfapi/bug-1093594.t
# prove -v ./tests/bugs/gfapi/bug-1319374-THIS-crash.t
# prove -v ./tests/bugs/gfapi/glfs_vol_set_IO_ERR.t
# prove -v ./tests/bugs/gfapi/bug-1032894.t
# prove -v ./tests/bugs/gfapi/bug-1447266/bug-1447266.t
# prove -v ./tests/bugs/gfapi/bug-1447266/1460514.t
# prove -v ./tests/bugs/bug-1371806_2.t
# prove -v ./tests/bugs/write-behind/bug-1058663.t
# prove -v ./tests/bugs/write-behind/bug-1279730.t
# prove -v ./tests/bugs/nl-cache/bug-1451588.t
# prove -v ./tests/bugs/bitrot/bug-1228680.t
# prove -v ./tests/bugs/bitrot/bug-1227996.t
# prove -v ./tests/bugs/bitrot/1207029-bitrot-daemon-should-start-on-valid-node.t
# prove -v ./tests/bugs/bitrot/bug-1245981.t
# prove -v ./tests/bugs/bitrot/1209752-volume-status-should-show-bitrot-scrub-info.t
# prove -v ./tests/bugs/bitrot/bug-1288490.t
# prove -v ./tests/bugs/bitrot/bug-1229134-bitd-not-support-vol-set.t
# prove -v ./tests/bugs/bitrot/bug-1210684-scrub-pause-resume-error-handling.t
# prove -v ./tests/bugs/bitrot/1209818-vol-info-show-scrub-process-properly.t
# prove -v ./tests/bugs/bitrot/1209751-bitrot-scrub-tunable-reset.t
# prove -v ./tests/bugs/geo-replication/bug-877293.t
# prove -v ./tests/bugs/geo-replication/bug-1111490.t
# prove -v ./tests/bugs/geo-replication/bug-1296496.t
# prove -v ./tests/bugs/bug-1371806.t
# prove -v ./tests/bugs/cli/bug-1030580.t
# prove -v ./tests/bugs/cli/bug-867252.t
# prove -v ./tests/bugs/cli/bug-770655.t
# prove -v ./tests/bugs/cli/bug-822830.t
# prove -v ./tests/bugs/cli/bug-949298.t
# prove -v ./tests/bugs/cli/bug-1047378.t
# prove -v ./tests/bugs/cli/bug-1353156-get-state-cli-validations.t
# prove -v ./tests/bugs/cli/bug-977246.t
# prove -v ./tests/bugs/cli/bug-1087487.t
# prove -v ./tests/bugs/cli/bug-969193.t
# prove -v ./tests/bugs/cli/bug-961307.t
# prove -v ./tests/bugs/cli/bug-1169302.t
# prove -v ./tests/bugs/cli/bug-1378842-volume-get-all.t
# prove -v ./tests/bugs/cli/bug-982174.t
# prove -v ./tests/bugs/cli/bug-1077682.t
# prove -v ./tests/bugs/cli/bug-764638.t
# prove -v ./tests/bugs/cli/bug-983317-volume-get.t
# prove -v ./tests/bugs/cli/bug-1113476.t
# prove -v ./tests/bugs/cli/bug-1047416.t
# prove -v ./tests/bugs/cli/bug-1004218.t
# prove -v ./tests/bugs/cli/bug-1022905.t
# prove -v ./tests/bugs/cli/bug-921215.t
# prove -v ./tests/bugs/cli/bug-1320388.t
# prove -v ./tests/bugs/md-cache/setxattr-prepoststat.t
# prove -v ./tests/bugs/md-cache/afr-stale-read.t
# prove -v ./tests/bugs/md-cache/bug-1211863.t
# prove -v ./tests/bugs/md-cache/bug-1476324.t
# prove -v ./tests/bugs/md-cache/bug-1211863_unlink.t
# prove -v ./tests/bugs/nfs/bug-915280.t
# prove -v ./tests/bugs/nfs/bug-1053579.t
# prove -v ./tests/bugs/nfs/zero-atime.t
# prove -v ./tests/bugs/nfs/socket-as-fifo.t
# prove -v ./tests/bugs/nfs/bug-1161092-nfs-acls.t
# prove -v ./tests/bugs/nfs/bug-1116503.t
# prove -v ./tests/bugs/nfs/bug-1210338.t
# prove -v ./tests/bugs/nfs/bug-974972.t
# prove -v ./tests/bugs/nfs/bug-1143880-fix-gNFSd-auth-crash.t
# prove -v ./tests/bugs/nfs/bug-1166862.t
# prove -v ./tests/bugs/nfs/bug-904065.t
# prove -v ./tests/bugs/nfs/bug-847622.t
# prove -v ./tests/bugs/nfs/bug-970070.t
# prove -v ./tests/bugs/nfs/bug-877885.t
# prove -v ./tests/bugs/nfs/showmount-many-clients.t
# prove -v ./tests/bugs/nfs/bug-1302948.t
# prove -v ./tests/bugs/nfs/bug-1157223-symlink-mounting.t
# prove -v ./tests/bugs/nfs/subdir-trailing-slash.t
# prove -v ./tests/bugs/logging/bug-823081.t
# prove -v ./tests/bugs/rpc/bug-921072.t
# prove -v ./tests/bugs/rpc/bug-1043886.t
# prove -v ./tests/bugs/rpc/bug-884452.t
# prove -v ./tests/bugs/rpc/bug-954057.t
# prove -v ./tests/bugs/rpc/bug-847624.t
# prove -v ./tests/bugs/unclassified/bug-1357397.t
# prove -v ./tests/bugs/unclassified/bug-874498.t
# prove -v ./tests/bugs/unclassified/bug-991622.t
# prove -v ./tests/bugs/unclassified/bug-1034085.t
# prove -v ./tests/bugs/bug-1584517.t
# prove -v ./tests/bugs/shard/bug-1251824.t
# prove -v ./tests/bugs/shard/bug-1259651.t
# prove -v ./tests/bugs/shard/bug-shard-zerofill.t
# prove -v ./tests/bugs/shard/parallel-truncate-read.t
# prove -v ./tests/bugs/shard/bug-1261773.t
# prove -v ./tests/bugs/shard/bug-1568521-EEXIST.t
# prove -v ./tests/bugs/shard/bug-1256580.t
# prove -v ./tests/bugs/shard/shard-append-test.t
# prove -v ./tests/bugs/shard/bug-1258334.t
# prove -v ./tests/bugs/shard/bug-shard-discard.t
# prove -v ./tests/bugs/shard/bug-1468483.t
# prove -v ./tests/bugs/shard/bug-1250855.t
# prove -v ./tests/bugs/shard/bug-1568521.t
# prove -v ./tests/bugs/shard/bug-1272986.t
# prove -v ./tests/bugs/shard/bug-1245547.t
# prove -v ./tests/bugs/shard/shard-inode-refcount-test.t
# prove -v ./tests/bugs/shard/bug-1488546.t
# prove -v ./tests/bugs/shard/unlinks-and-renames.t
# prove -v ./tests/bugs/shard/bug-1260637.t
# prove -v ./tests/bugs/shard/zero-flag.t
# prove -v ./tests/bugs/shard/bug-1342298.t
# prove -v ./tests/bugs/shard/bug-1248887.t
# prove -v ./tests/bugs/bug-1258069.t
# prove -v ./tests/bugs/bug-1371806_3.t
# prove -v ./tests/bugs/ec/bug-1161886.t
# prove -v ./tests/bugs/ec/bug-1161621.t
# prove -v ./tests/bugs/ec/bug-1251446.t
# prove -v ./tests/bugs/ec/bug-1179050.t
# prove -v ./tests/bugs/ec/bug-1547662.t
# prove -v ./tests/bugs/ec/bug-1304988.t
# prove -v ./tests/bugs/ec/bug-1188145.t
# prove -v ./tests/bugs/ec/bug-1187474.t
# prove -v ./tests/bugs/ec/bug-1227869.t
# prove -v ./tests/bugs/ec/bug-1236065.t
# prove -v ./tests/features/weighted-rebalance.t
# prove -v ./tests/features/mandatory-lock-forced.t
# prove -v ./tests/features/trash.t
# prove -v ./tests/features/lock_revocation.t
# prove -v ./tests/features/subdir-mount.t
# prove -v ./tests/features/readdir-ahead.t
# prove -v ./tests/features/glupy.t
# prove -v ./tests/features/delay-gen.t
# prove -v ./tests/features/ssl-authz.t
# prove -v ./tests/features/lock-migration/lkmigration-set-option.t
# prove -v ./tests/features/worm.t
# prove -v ./tests/features/ssl-ciphers.t
# prove -v ./tests/features/worm_sh.t
# prove -v ./tests/features/glfs-lease.t
# prove -v ./tests/features/unhashed-auto.t
# prove -v ./tests/features/ipc.t
# prove -v ./tests/features/fdl-overflow.t
# prove -v ./tests/features/recon.t
# prove -v ./tests/features/fdl.t
# prove -v ./tests/features/nuke.t
# prove -v ./tests/gfid2path/gfid2path_nfs.t
# prove -v ./tests/gfid2path/get-gfid-to-path.t
# prove -v ./tests/gfid2path/gfid2path_fuse.t
# prove -v ./tests/gfid2path/block-mount-access.t
# prove -v ./tests/bitrot/bug-1294786.t
# prove -v ./tests/bitrot/br-state-check.t
# prove -v ./tests/bitrot/bug-1373520.t
# prove -v ./tests/bitrot/bug-1207627-bitrot-scrub-status.t
# prove -v ./tests/bitrot/bug-1244613.t
# prove -v ./tests/bitrot/bug-internal-xattrs-check-1243391.t
# prove -v ./tests/bitrot/bug-1221914.t
# prove -v ./tests/bitrot/br-stub.t
# prove -v ./tests/00-geo-rep/00-georep-verify-setup.t
# prove -v ./tests/00-geo-rep/georep-basic-dr-rsync.t
# prove -v ./tests/00-geo-rep/georep-basic-dr-tarssh.t
