// Code generated by protoc-gen-go.
// source: peer-svc.proto
// DO NOT EDIT!

/*
Package services is a generated protocol buffer package.

It is generated from these files:
	peer-svc.proto

It has these top-level messages:
	RPCPeerAddReq
	RPCPeerAddResp
	RPCEtcdEnvReq
	RPCEtcdEnvResp
*/
package services

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RPCPeerAddReq struct {
	Name             *string  `protobuf:"bytes,1,req" json:"Name,omitempty"`
	Addresses        []string `protobuf:"bytes,2,rep" json:"Addresses,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *RPCPeerAddReq) Reset()         { *m = RPCPeerAddReq{} }
func (m *RPCPeerAddReq) String() string { return proto.CompactTextString(m) }
func (*RPCPeerAddReq) ProtoMessage()    {}

func (m *RPCPeerAddReq) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *RPCPeerAddReq) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type RPCPeerAddResp struct {
	OpRet            *int32  `protobuf:"varint,1,req" json:"OpRet,omitempty"`
	OpError          *string `protobuf:"bytes,2,req" json:"OpError,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RPCPeerAddResp) Reset()         { *m = RPCPeerAddResp{} }
func (m *RPCPeerAddResp) String() string { return proto.CompactTextString(m) }
func (*RPCPeerAddResp) ProtoMessage()    {}

func (m *RPCPeerAddResp) GetOpRet() int32 {
	if m != nil && m.OpRet != nil {
		return *m.OpRet
	}
	return 0
}

func (m *RPCPeerAddResp) GetOpError() string {
	if m != nil && m.OpError != nil {
		return *m.OpError
	}
	return ""
}

type RPCEtcdEnvReq struct {
	PeerName         *string `protobuf:"bytes,1,req" json:"PeerName,omitempty"`
	Name             *string `protobuf:"bytes,2,req" json:"Name,omitempty"`
	InitialCluster   *string `protobuf:"bytes,3,req" json:"InitialCluster,omitempty"`
	ClusterState     *string `protobuf:"bytes,4,req" json:"ClusterState,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RPCEtcdEnvReq) Reset()         { *m = RPCEtcdEnvReq{} }
func (m *RPCEtcdEnvReq) String() string { return proto.CompactTextString(m) }
func (*RPCEtcdEnvReq) ProtoMessage()    {}

func (m *RPCEtcdEnvReq) GetPeerName() string {
	if m != nil && m.PeerName != nil {
		return *m.PeerName
	}
	return ""
}

func (m *RPCEtcdEnvReq) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *RPCEtcdEnvReq) GetInitialCluster() string {
	if m != nil && m.InitialCluster != nil {
		return *m.InitialCluster
	}
	return ""
}

func (m *RPCEtcdEnvReq) GetClusterState() string {
	if m != nil && m.ClusterState != nil {
		return *m.ClusterState
	}
	return ""
}

type RPCEtcdEnvResp struct {
	OpRet            *int32  `protobuf:"varint,1,req" json:"OpRet,omitempty"`
	OpError          *string `protobuf:"bytes,2,req" json:"OpError,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RPCEtcdEnvResp) Reset()         { *m = RPCEtcdEnvResp{} }
func (m *RPCEtcdEnvResp) String() string { return proto.CompactTextString(m) }
func (*RPCEtcdEnvResp) ProtoMessage()    {}

func (m *RPCEtcdEnvResp) GetOpRet() int32 {
	if m != nil && m.OpRet != nil {
		return *m.OpRet
	}
	return 0
}

func (m *RPCEtcdEnvResp) GetOpError() string {
	if m != nil && m.OpError != nil {
		return *m.OpError
	}
	return ""
}
