// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction-rpc.proto

/*
Package transaction is a generated protocol buffer package.

It is generated from these files:
	transaction-rpc.proto

It has these top-level messages:
	TxnStepReq
	TxnStepResp
*/
package transaction

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TxnStepReq struct {
	StepFunc string `protobuf:"bytes,1,opt,name=StepFunc" json:"StepFunc,omitempty"`
	Context  []byte `protobuf:"bytes,2,opt,name=Context,proto3" json:"Context,omitempty"`
}

func (m *TxnStepReq) Reset()                    { *m = TxnStepReq{} }
func (m *TxnStepReq) String() string            { return proto.CompactTextString(m) }
func (*TxnStepReq) ProtoMessage()               {}
func (*TxnStepReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TxnStepReq) GetStepFunc() string {
	if m != nil {
		return m.StepFunc
	}
	return ""
}

func (m *TxnStepReq) GetContext() []byte {
	if m != nil {
		return m.Context
	}
	return nil
}

type TxnStepResp struct {
	Error string `protobuf:"bytes,1,opt,name=Error" json:"Error,omitempty"`
}

func (m *TxnStepResp) Reset()                    { *m = TxnStepResp{} }
func (m *TxnStepResp) String() string            { return proto.CompactTextString(m) }
func (*TxnStepResp) ProtoMessage()               {}
func (*TxnStepResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TxnStepResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*TxnStepReq)(nil), "transaction.TxnStepReq")
	proto.RegisterType((*TxnStepResp)(nil), "transaction.TxnStepResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TxnSvc service

type TxnSvcClient interface {
	RunStep(ctx context.Context, in *TxnStepReq, opts ...grpc.CallOption) (*TxnStepResp, error)
}

type txnSvcClient struct {
	cc *grpc.ClientConn
}

func NewTxnSvcClient(cc *grpc.ClientConn) TxnSvcClient {
	return &txnSvcClient{cc}
}

func (c *txnSvcClient) RunStep(ctx context.Context, in *TxnStepReq, opts ...grpc.CallOption) (*TxnStepResp, error) {
	out := new(TxnStepResp)
	err := grpc.Invoke(ctx, "/transaction.TxnSvc/RunStep", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TxnSvc service

type TxnSvcServer interface {
	RunStep(context.Context, *TxnStepReq) (*TxnStepResp, error)
}

func RegisterTxnSvcServer(s *grpc.Server, srv TxnSvcServer) {
	s.RegisterService(&_TxnSvc_serviceDesc, srv)
}

func _TxnSvc_RunStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxnStepReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TxnSvcServer).RunStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transaction.TxnSvc/RunStep",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TxnSvcServer).RunStep(ctx, req.(*TxnStepReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _TxnSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "transaction.TxnSvc",
	HandlerType: (*TxnSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunStep",
			Handler:    _TxnSvc_RunStep_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction-rpc.proto",
}

func init() { proto.RegisterFile("transaction-rpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x29, 0x4a, 0xcc,
	0x2b, 0x4e, 0x4c, 0x2e, 0xc9, 0xcc, 0xcf, 0xd3, 0x2d, 0x2a, 0x48, 0xd6, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x46, 0x12, 0x56, 0x72, 0xe2, 0xe2, 0x0a, 0xa9, 0xc8, 0x0b, 0x2e, 0x49, 0x2d,
	0x08, 0x4a, 0x2d, 0x14, 0x92, 0xe2, 0xe2, 0x00, 0x31, 0xdd, 0x4a, 0xf3, 0x92, 0x25, 0x18, 0x15,
	0x18, 0x35, 0x38, 0x83, 0xe0, 0x7c, 0x21, 0x09, 0x2e, 0x76, 0xe7, 0xfc, 0xbc, 0x92, 0xd4, 0x8a,
	0x12, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0x18, 0x57, 0x49, 0x99, 0x8b, 0x1b, 0x6e, 0x46,
	0x71, 0x81, 0x90, 0x08, 0x17, 0xab, 0x6b, 0x51, 0x51, 0x7e, 0x11, 0xd4, 0x04, 0x08, 0xc7, 0xc8,
	0x83, 0x8b, 0x0d, 0xa4, 0xa8, 0x2c, 0x59, 0xc8, 0x8e, 0x8b, 0x3d, 0xa8, 0x14, 0xac, 0x5c, 0x48,
	0x5c, 0x0f, 0xc9, 0x2d, 0x7a, 0x08, 0x87, 0x48, 0x49, 0x60, 0x97, 0x28, 0x2e, 0x50, 0x62, 0x48,
	0x62, 0x03, 0x7b, 0xc3, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x65, 0x9b, 0x63, 0xdf, 0x00,
	0x00, 0x00,
}
