// Code generated by "stringer -type=VolType"; DO NOT EDIT

package volume

import "fmt"

const _VolType_name = "DistributeReplicateDisperseDistReplicateDistDisperse"

var _VolType_index = [...]uint8{0, 10, 19, 27, 40, 52}

func (i VolType) String() string {
	if i >= VolType(len(_VolType_index)-1) {
		return fmt.Sprintf("VolType(%d)", i)
	}
	return _VolType_name[_VolType_index[i]:_VolType_index[i+1]]
}
