---
- hosts: builder
  remote_user: root
  gather_facts: no

  tasks:
    - name: Upgrade to latest packages
      yum:
        name: "*"
        state: latest

    # TODO: Currently using centos-ci nightly builds. Need to move to using the
    # nightly bits that get produced by the build.gluster.org nightly pipeline.
    - name: Add nightly repositories
      get_url:
        url: "{{ item.url }}"
        dest: "{{ item.path }}"
        mode: 0644
        owner: root
      with_items:
        - {url: "http://artifacts.ci.centos.org/gluster/nightly/release-6.repo", path: "/etc/yum.repos.d/glusterfs-nightly.repo"}
        - {url: "http://artifacts.ci.centos.org/gluster/gd2-nightly/gd2-master.repo", path: "/etc/yum.repos.d/glusterd2-nightly.repo"}
        - {url: "http://artifacts.ci.centos.org/gluster/gluster-prometheus-nightly/gluster-prometheus-master.repo", path: "/etc/yum.repos.d/gluster-prometheus-nightly.repo"}

    # Required for correct userspace-rcu versions. The version available from
    # centos-release-gluster does not work ATM with the nightly builds
    - name: Enable epel repository
      yum:
        name: epel-release
        state: present

    - name: Install Gluster, GD2 and dependencies
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - glusterfs-server
        - glusterfs-geo-replication
        - glusterd2
        - lvm2
        - xfsprogs
        - gluster-prometheus-exporter

    - name: Clean yum cache
      command: yum clean all
      args:
        warn: no

    - name: Remove lvm2 tmpfiles config
      file:
        path: /usr/lib/tmpfiles.d/lvm2.conf
        state: absent

    - name: Ensure /run/{lvm,udev} is present
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /run/lvm
        - /run/udev

    # Using shell here instead of find/file modules as this is much easier
    - name: Cleanup systemd targets
      shell: |
        rm -f /etc/systemd/system/*.wants/*
        rm -f /lib/systemd/system/multi-user.target.wants/*
        rm -f /lib/systemd/system/local-fs.target.wants/*
        rm -f /lib/systemd/system/basic.target.wants/*
        rm -f /lib/systemd/system/anaconda.target.wants/*
        rm -f /lib/systemd/system/sockets.target.wants/*udev*
        rm -f /lib/systemd/system/sockets.target.wants/*initctl*
        find /lib/systemd/system/sysinit.target.wants -type l -not -name systemd-tmpfiles-setup.service -exec rm -f {} \;
      args:
        warn: no

    - name: Mask unneeded systemd services
      shell: |
        systemctl mask getty.target
        systemctl mask systemd-udev-trigger.service
        systemctl mask systemd-udevd.service
        systemctl mask systemd-udevd.socket
        systemctl mask systemd-udevd-kernel.socket
        systemctl mask lvm2-lvmetad.service
        systemctl mask lvm2-lvmetad.socket
      args:
        warn: no

    - name: Create override directory for glusterd2.service
      file:
        path: /etc/systemd/system/glusterd2.service.d
        state: directory

    # This makes systemd pass environment variables set for GD2 by kubernetes
    - name: Enable PassEnvironment override for glusterd2.service
      ini_file:
        path: /etc/systemd/system/glusterd2.service.d/override.conf
        section: Service
        option: PassEnvironment
        # PassEnvironment requires that each variable be mentioned individually
        # More variables will need to be added here as required
        value: GD2_ETCDENDPOINTS GD2_CLUSTER_ID GD2_RESTAUTH GD2_CLIENTADDRESS GD2_PEERADDRESS

    - name: Create /etc/sysconfig/glusterd2/
      file:
        path: /etc/sysconfig/glusterd2
        state: directory

    - name: Disable embedded etcd for GD2
      lineinfile:
        path: /etc/sysconfig/glusterd2/noembed
        create: yes
        line: GD2_NOEMBED=true
        state: present

    - name: Configure gluster-exporter to use glusterd2
      replace:
        path: /etc/gluster-exporter/gluster-exporter.toml
        regexp: '^gluster-mgmt\s*=.*'
        replace: 'gluster-mgmt = "glusterd2"'

    - name: Configure gluster-exporter to use glusterd2 workdir
      replace:
        path: /etc/gluster-exporter/gluster-exporter.toml
        regexp: '^glusterd-dir\s*=.*'
        replace: 'glusterd-dir = "/var/lib/glusterd2"'

    - name: Create override directory for gluster-exporter.service
      file:
        path: /etc/systemd/system/gluster-exporter.service.d
        state: directory

    # This makes systemd pass environment variables set for
    # glusterd2/gluster-exporter by kubernetes
    - name: Enable PassEnvironment override for gluster-exporter.service
      ini_file:
        path: /etc/systemd/system/gluster-exporter.service.d/override.conf
        section: Service
        option: PassEnvironment
        # PassEnvironment requires that each variable be mentioned individually
        # More variables will need to be added here as required
        value: GD2_ENDPOINTS

    # Using direct systemctl here as the way the service/systemd modules work
    # requires dbus, which is not available in the container
    - name: Enable required services
      command: systemctl enable {{ item }}
      args:
        warn: false
      loop:
        - glusterd2.service
        - gluster-exporter.service
