// Code generated by "stringer -type=fsType"; DO NOT EDIT.

package volumecommands

import "fmt"

const (
	_fsType_name_0 = "smb"
	_fsType_name_1 = "nfs"
	_fsType_name_2 = "ext"
	_fsType_name_3 = "zfs"
	_fsType_name_4 = "xfs"
	_fsType_name_5 = "fuse"
	_fsType_name_6 = "btrfs"
)

var (
	_fsType_index_0 = [...]uint8{0, 3}
	_fsType_index_1 = [...]uint8{0, 3}
	_fsType_index_2 = [...]uint8{0, 3}
	_fsType_index_3 = [...]uint8{0, 3}
	_fsType_index_4 = [...]uint8{0, 3}
	_fsType_index_5 = [...]uint8{0, 4}
	_fsType_index_6 = [...]uint8{0, 5}
)

func (i fsType) String() string {
	switch {
	case i == 20859:
		return _fsType_name_0
	case i == 26985:
		return _fsType_name_1
	case i == 61267:
		return _fsType_name_2
	case i == 12235020:
		return _fsType_name_3
	case i == 1481003842:
		return _fsType_name_4
	case i == 1702057286:
		return _fsType_name_5
	case i == 2435016766:
		return _fsType_name_6
	default:
		return fmt.Sprintf("fsType(%d)", i)
	}
}
