package volumecommands

import (
	"github.com/gluster/glusterd2/pkg/api"
)

// defaultGroupOptions maps from a profile name to a set of options
var defaultGroupOptions = map[string][]api.VolumeOption{
	"profile.gluster-block": {api.VolumeOption{Name: "performance.quick-read", OnValue: "off", OffValue: "on"},
		api.VolumeOption{Name: "performance.read-ahead", OnValue: "off", OffValue: "on"},
		api.VolumeOption{Name: "performance.io-cache", OnValue: "off", OffValue: "on"},
		api.VolumeOption{Name: "performance.stat-prefetch", OnValue: "off", OffValue: "on"},
		api.VolumeOption{Name: "performance.open-behind", OnValue: "off", OffValue: "on"},
		api.VolumeOption{Name: "performance.readdir-ahead", OnValue: "off", OffValue: "on"},
		api.VolumeOption{Name: "performance.strict-o-direct", OnValue: "on", OffValue: "off"},
		api.VolumeOption{Name: "network.remote-dio", OnValue: "disable", OffValue: "enable"},
		api.VolumeOption{Name: "cluster.eager-lock", OnValue: "disable", OffValue: "enable"},
		api.VolumeOption{Name: "cluster.quorum-type", OnValue: "auto", OffValue: "none"},
		api.VolumeOption{Name: "cluster.data-self-heal-algorithm", OnValue: "full", OffValue: "reset"},
		api.VolumeOption{Name: "cluster.locking-scheme", OnValue: "granular", OffValue: "full"},
		api.VolumeOption{Name: "cluster.shd-max-threads", OnValue: "8", OffValue: "1"},
		api.VolumeOption{Name: "cluster.shd-wait-qlength", OnValue: "10000", OffValue: "1024"},
		api.VolumeOption{Name: "features.shard", OnValue: "on", OffValue: "off"},
		api.VolumeOption{Name: "features.shard-block-size", OnValue: "64MB", OffValue: "512MB"},
		api.VolumeOption{Name: "user.cifs", OnValue: "off", OffValue: "on"},
		api.VolumeOption{Name: "server.allow-insecure", OnValue: "on", OffValue: "off"}},
	"profile.nl-cache": {api.VolumeOption{Name: "features.cache-invalidation", OnValue: "on", OffValue: "off"},
		api.VolumeOption{Name: "features.cache-invalidation-timeout", OnValue: "600", OffValue: "60"},
		api.VolumeOption{Name: "performance.nl-cache", OnValue: "on", OffValue: "off"},
		api.VolumeOption{Name: "performance.nl-cache-timeout", OnValue: "600", OffValue: "600"},
		api.VolumeOption{Name: "network.inode-lru-limit", OnValue: "50000", OffValue: "16384"}},
	"profile.metadata-cache": {api.VolumeOption{Name: "features.cache-invalidation", OnValue: "on", OffValue: "off"},
		api.VolumeOption{Name: "features.cache-invalidation-timeout", OnValue: "600", OffValue: "60"},
		api.VolumeOption{Name: "performance.stat-prefetch", OnValue: "on", OffValue: "off"},
		api.VolumeOption{Name: "performance.cache-invalidation", OnValue: "on", OffValue: "off"},
		api.VolumeOption{Name: "performance.md-cache-timeout", OnValue: "600", OffValue: "600"},
		api.VolumeOption{Name: "network.inode-lru-limit", OnValue: "50000", OffValue: "16384"}},
	"profile.virt": {api.VolumeOption{Name: "performance.quick-read", OnValue: "off", OffValue: "on"},
		api.VolumeOption{Name: "performance.read-ahead", OnValue: "off", OffValue: "on"},
		api.VolumeOption{Name: "performance.io-cache", OnValue: "off", OffValue: "on"},
		api.VolumeOption{Name: "performance.low-prio-threads", OnValue: "32", OffValue: "32"},
		api.VolumeOption{Name: "network.remote-dio", OnValue: "enable", OffValue: "disable"},
		api.VolumeOption{Name: "cluster.eager-lock", OnValue: "enable", OffValue: "disable"},
		api.VolumeOption{Name: "cluster.quorum-type", OnValue: "auto", OffValue: "none"},
		api.VolumeOption{Name: "cluster.server-quorum-type", OnValue: "server", OffValue: "none"},
		api.VolumeOption{Name: "cluster.data-self-heal-algorithm", OnValue: "full", OffValue: "reset"},
		api.VolumeOption{Name: "cluster.locking-scheme", OnValue: "granular", OffValue: "full"},
		api.VolumeOption{Name: "cluster.shd-max-threads", OnValue: "8", OffValue: "1"},
		api.VolumeOption{Name: "cluster.shd-wait-qlength", OnValue: "10000", OffValue: "1024"},
		api.VolumeOption{Name: "features.shard", OnValue: "on", OffValue: "off"},
		api.VolumeOption{Name: "user.cifs", OnValue: "off", OffValue: "on"}},
	"profile.test": {api.VolumeOption{Name: "afr.eager-lock", OnValue: "on", OffValue: "off"},
		api.VolumeOption{Name: "gfproxy.afr.eager-lock", OnValue: "on", OffValue: "off"}},
}
